project:
  type: website
  
cache: true

website:
  title: "siteR"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: aula1.qmd
        text: Introdução
        icon: info-circle
      - href: aula2.qmd
        text: Gráficos
        icon: graph-up-arrow
      - href: aula3.qmd
        text: Test T
        icon: person-vcard
      - href: aula4.qmd
        text: Anova
        icon: grid-3x3-gap
      - href: aula5.qmd
        text: Teste de médias
        icon: list-check

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

