---
title: "Aula 5"
editor_options: 
  chunk_output_type: inline
---
## 2 testes de normalidade Shapiro e Bartllet


## Carrega dados

```{r}
library(tidyverse)
insetos <- InsectSprays
insetos |> ggplot (aes(spray, count)) + geom_boxplot(outlier.colour = NA) + geom_jitter (width = 0.1)



```

##MODELO DE ANOVA

```{r}

m1 <- lm(count~spray, data = insetos)
m1
summary(m1)
anova(m1)

hist(m1$residuals)
shapiro.test(m1$residuals)
bartlett.test(count~spray, data = insetos)

library(performance)
check_normality(m1)
check_heteroscedasticity(m1)


##dessa forma vamos usar o teste não paramétrico

kruskal.test(count~spray, data = insetos)

library(DHARMa)

plot(simulateResiduals(m1))

insetos2 <- insetos |> mutate(count2 = sqrt (count))
insetos2

##agora o modelo resposta será o count2

m2 <- lm(sqrt (count) ~spray, data = insetos2)
m2
summary(m2)
anova(m2)

hist(m2$residuals)
shapiro.test(m2$residuals)
bartlett.test(count2~spray, data = insetos2)

insetos2 |> ggplot (aes(spray, count2)) + geom_boxplot(outlier.colour = NA) + geom_jitter (width = 0.1)

library(performance)
check_normality(m2)
check_heteroscedasticity(m2)

library(DHARMa)

plot(simulateResiduals(m2))

library(emmeans)
medias2 <- emmeans (m2,~ spray, type  = "response")
medias2
library(multcomp)
cld(medias2, Letters = LETTERS)

library(agricolae)
k <- kruskal(insetos$count, insetos$spray)
k


##GLM com A FAMILIA E FUNÇÃO DE LIGAÇÃO

m3 <- glm(count ~ spray, family = poisson(link = "log"), data = insetos)

plot(simulateResiduals(m3))

df3 <- cld(emmeans(m3,~ spray, type = "response"), Letters = LETTERS)

df3 |> 
  ggplot(aes(spray, rate, label = .group)) + geom_point() + geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.1) + ylim(0, 25) + geom_text(aes(y = asymp.UCL), vjust = -0.5, size = 4) + theme_classic() +
  labs(x = "Inseticida", y = "Insetos vivos (contagem)")+coord_flip()

#o coord_flip inverte o x com o y

```




